services:
  db:
    image: "postgis/postgis:16-3.4-alpine"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: market_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    command: >
      postgres
      -c max_locks_per_transaction=256
      -c shared_buffers=256MB
      -c work_mem=8MB
      -c maintenance_work_mem=128MB
      -c statement_timeout=600000
      -c lock_timeout=120000
      -c idle_in_transaction_session_timeout=600000
      -c max_connections=200
      -c effective_cache_size=1GB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - node:20-alpine
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: market_db_2
      DB_PORT: 5432
      NODE_ENV: production
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: "no"
    # command: sh -c "pnpm migrate && pnpm seed && pnpm test"
    command: sh -c "pnpm migrate"

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@market.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped

  dbdocs:
    image: node:20-alpine
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - dbml_node_modules:/usr/src/app/node_modules
      - npm_cache:/root/.npm
    working_dir: /usr/src/app
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: market_db
      DB_PORT: 5432
    command: >
      sh -c "
      if [ ! -f /usr/local/bin/db2dbml ]; then
        echo 'Installing @dbml/cli...' &&
        npm install -g @dbml/cli
      fi &&
      echo 'Generating DBML schema...' &&
      db2dbml postgres 'postgresql://postgres:postgres@db:5432/market_db?schemas=public' -o ./schema.dbml &&
      echo '=== DBML SCHEMA ===' &&
      cat ./schema.dbml
      "
    restart: "no"

volumes:
  db_data:
  pgadmin_data:
  dbml_node_modules:
  npm_cache:
