Table "spatial_ref_sys" {
  "srid" int4 [pk, not null]
  "auth_name" varchar(256)
  "auth_srid" int4
  "srtext" varchar(2048)
  "proj4text" varchar(2048)
}

Table "__migrations" {
  "id" int4 [pk, not null, increment]
  "name" varchar(255) [unique, not null]
  "applied_at" timestamptz [default: `CURRENT_TIMESTAMP`]
  "checksum" varchar(64) [not null]
}
